### ISSUE TITLE
Regarding the s3 setup in the cloudformation script 

### ISSUE THREAD

**Issue by zamkp** [aws-quickstart/quickstart-mongodb#37]
Hi 
I am new in cloud formation and have the following queries  below please help me to sort out this 

1) Why are we using dynamo-db is it necessary to run the mongo replication set ? How can I remove the dynamo-db from part from the cloud formation script? 

How can I use my own s3 bucket instead of aws-quickstart what are the steps that I need to follow?

**Comment by vsnyc** [comment]
## Purpose of dynamodb table

Take a look at usage of orchestrator script within init_replica.sh. Dynamodb table is used for a few things:

1. Primary node creates the dynamodb table
2. Each node add its own ip address and status as WORKING. Primary waits for at least 3 nodes in WORKING status and then saves the IP addresses.
3. Each node marks its status as FINISHED after mongod service has been started
4. Primary waits for 3 nodes to be in FINISHED state before proceeding with the security steup
5. The primary node generates a key using openssl and saves it in dynamodb
6. Secondary nodes download that key from dynamodb and save it to local mongo config
7. Each node marks its status as SECURED after doing adding the security config
8. Primary waits for 3 nodes to be in SECURED state
9. Primary deletes the dynamodb table

If you want to remove the dynamodb table, you can modify `init_repica.sh` script to not create dynamodb table and do the above orchestration in some other way that works for you.

## Using your own S3 bucket

Steps are below:
1. Clone this git repo recursively on your local device. Note the usage of git ssh authentication below because the VPC and Linux submodules are setup with git ssh url:
   `git clone --recurse-submodules git@github.com:aws-quickstart/quickstart-mongodb.git`
2. Copy the cloned repo to your S3 bucket e.g. the following command from quickstart-mongodb directory:
`aws s3 sync . s3://<YOUR_BUCKET>/quickstart-mongodb/`
3. When launching the template in cloudformation, specify the url of your uploaded template e.g.
`https://s3.amazonaws.com/<YOUR_BUCKET>/quickstart-mongodb/templates/mongodb-master.template`
4. When supplying inputs for various parameters in CloudFormation either via console or CLI, make sure you modify the value of `QSS3BucketName` parameter to point to your S3 bucket and `QSS3KeyPrefix` parameter to the prefix where you uploaded the project to, keeping the trailing slash. If you follow point 2 above then prefix will remain the default: `quickstart-mongodb/`

**Comment by zamkp** [comment]
Thanks a lot.

 In this cloudformation template, the role has full s3 access to all buckets (line 446). How can I restrict the access to the single bucket? Also can you tell me what this policy is doing in this template?

Please help me

**Comment by vsnyc** [comment]
Hi, I'm reviewing the `MongoDBNodeIAMRole` and will update the template.

**Comment by vsnyc** [comment]
I've updated the role permissions at commit: c086a750174226c6b6bea5e53ee89b3fd353088a. Please open a new issue if you have any further questions.

**Comment by zamkp** [comment]
Thanks  for you update 
 
I have the following queries below please help me to sort out this

1) Backup – how do we handle the backup? 

2)  If one of the instances becomes decommission how will we recreate this node to have 3-node-cluster again? 
3) How can we prevent losing all data?

4) How can we upgrade the mongo version in future?

**Comment by vsnyc** [comment]
@zamkp Please open a new issue for each independent questions in future. Resolved issues can sometimes go unnoticed.

> Backup – how do we handle the backup?

You could schedule EBS snapshot backups. See this for details. https://docs.mongodb.com/manual/core/backups/

> If one of the instances becomes decommission how will we recreate this node to have 3-node-cluster again?

What is this referring to? A EC2 host failure or an user action? If it is the former the EC2 instances are setup with autorecovery. See this issue for details: https://github.com/aws-quickstart/quickstart-mongodb/issues/30

> How can we prevent losing all data?

I'm not quite sure what the concern is. Does [this](https://aws.amazon.com/ebs/details/) help? See the Amazon EBS Availability and Durability section. 

> How can we upgrade the mongo version in future?

Once you have an installed configuration, the suggested way is to follow MongoDB's documented upgrade process, e.g. [Upgrading to MongoDB 4.0](https://docs.mongodb.com/manual/release-notes/4.0-upgrade-replica-set/)
