### ISSUE TITLE
Can I use T3/T2/A1 instances?

### ISSUE THREAD

**Issue by MrPeker** [aws-quickstart/quickstart-mongodb#41]
Hi, can I use T3/T2/A1 instances?

**Comment by vsnyc** [comment]
Yes, you can use T3 and T2 without any issues. Since A1 is ARM based, it may or may not work, please try and let us know your feedback. 

If you'd like to work with these instance types, follow the steps below.

1. Follow these steps in the Quick Start Contributor's Guide: [Make the Quick Start your own](https://aws-quickstart.github.io/option1.html)
2. Modify `NodeInstanceType` in all the three templates: `mongodb-master.template`, `mongodb.template`, and `mongodb-node.template` to allow the instance type you are interested in.
3. Deploy the updated code and test.
