### ISSUE TITLE
Changing node name tag breaks template

### ISSUE THREAD

**Issue by cirrushq-karan** [aws-quickstart/quickstart-mongodb#42]
Hello, in your mongodb.yaml template there's a parameter called ReplicaNodeNameTag which defines the name of the node. I found that changing this seems to cause the CloudFormation to eventually timeout. It seems orchestrator.sh becomes stuck in an infinite loop and the log just says "Waiting for Master to create table..". I wanted to name my nodes along the lines of db-primary0.mydomain.com, db-secondary0.mydomain.com, db-secondary1.mydomain.com, but it doesn't work and the CloudFormation template timeout. 

Is there a hard link between the node name and scripts? Is it possible to change the node name tag in the template at all? I find that if I keep the original names and append something at the end it still works okay. For example PrimaryReplicaNode0-Dev or SecondaryReplicaNode0-UAT.

**Comment by proton1k** [comment]
Hi @cirrushq-karan, did you resolve this question?

**Comment by vsnyc** [comment]
Sorry for the delay. Yes, right now the script requires the node name to start with `Primary...`, see this code:

https://github.com/aws-quickstart/quickstart-mongodb/blob/master/scripts/init_replica.sh#L56-L68

I can update the regex: https://github.com/aws-quickstart/quickstart-mongodb/blob/master/scripts/init_replica.sh#L23, to accept values like `db-primary0.mydomain.com`

If we change this line:
https://github.com/aws-quickstart/quickstart-mongodb/blob/master/scripts/init_replica.sh#L23

from:
```
    result=`echo $tags | jq '.[]' | jq $filter.Value | sed s/\"//g | sed s/Primary.*/Primary/g | tr -d '\n'`
```
to
```
    result=`echo $tags | jq '.[]' | jq $filter.Value | sed s/\"//g | sed s/.*[Pp]rimary.*/Primary/g | tr -d '\n'`
```

That should handle the above scenario.

**Comment by noname77** [comment]
This is old, but since its still open and valid:

I had a similar issue. I didn't wan't to have a permanent **Primary** string in a node name as the node type can change in case of failures.

I modified the mongodb QuickStart to include a new `InitialNodeType` tag which is used instead of the `Name` in init_replica.sh script

With my fork you can set the values of `ReplicaNodeNameTag` to your liking and still get the CloudFormation to succeed

### Links

[Fork](https://github.com/noname77/quickstart-mongodb/tree/allow-custom-instance-name) with the fixes on `allow-custom-instance-name` branch.
[Guide](https://aws.amazon.com/blogs/infrastructure-and-automation/customize-aws-quick-start/) on how to deploy customised QuickStart from your bucket
[PR](https://github.com/aws-quickstart/quickstart-mongodb/pull/82)

**Comment by vsnyc** [comment]
Closing old issues. This repository is now deprecated in favor of of https://github.com/aws-quickstart/quickstart-mongodb-atlas.
