### ISSUE TITLE
Bastion Auto scaling group: received 1 FAILURE signal(s) out of 1

### ISSUE THREAD

**Issue by salander0411** [aws-quickstart/quickstart-mongodb#48]
[Bastion Auto scaling group] received 1 FAILURE signal(s) out of 1. Unable to satify 100% MinSuccessfulInstancesPercent requirement.

I'm using launch mongodb into a new VPC 
region: us-east-1 / ap-northeast-1 , all failed with the same failure message above.
mongo version : 4.0
s3 folders all using the default ones, I only revise mongo password & username etc.

**Comment by salander0411** [comment]
seems like that cannot download file from:

https://aws-quickstart-us-east-1.s3.us-east-1.amazonaws.com/quickstart-mongodb/scripts/bastion_bootstrap.sh

please help to confirm. 

Also, why bastion_bootstrap.sh is not uploaded to github scripts/ folder?  It's hard for users to troubleshooting or revise because we cannot get this file

**Comment by vsnyc** [comment]
@salander0411 Could you explain how you launched this? The set of parameters used will be helpful to begin with. The path to bastion_bootstrap.sh script that you have is incorrect, the expected path should be the below and the file exists. 

https://aws-quickstart-us-east-1.s3.us-east-1.amazonaws.com/quickstart-mongodb/submodules/quickstart-linux-bastion/scripts/bastion_bootstrap.sh

Relevant lines of code:
* Bastion [template URL](https://github.com/aws-quickstart/quickstart-mongodb/blob/master/templates/mongodb-master.template#L508-L520)
* Bastion [QSS3KeyPrefix](https://github.com/aws-quickstart/quickstart-mongodb/blob/master/templates/mongodb-master.template#L550-L552)

> Also, why bastion_bootstrap.sh is not uploaded to github scripts/ folder? It's hard for users to troubleshooting or revise because we cannot get this file

Because the Linux bastion quick start is added as a git submodule and the bastion_bootstrap.sh is supposed to come from there. If you're copying from GitHub, [Adopt a Quick Start](https://aws-quickstart.github.io/option1.html) in our Contributor's Guide should help.

**Comment by salander0411** [comment]
Hi @vsnyc , the script is a personal guess as I failed to launch the template yesterday. After your explanation I have checked the cloudformation parameter again to find that the replicaSet is the default 3 while I only choose 2 AZs which leads to the failure. Thanks for you quick response and patience : )
