### ISSUE TITLE
Help connecting to instances

### ISSUE THREAD

**Issue by vitor-kato** [aws-quickstart/quickstart-mongodb#52]
Hello, I'm having some difficulty in connecting to the database using the NAT gateway. Being kinda new to the aws resources.

How should I proceed to connect from the outside (internet) to the database?

**Comment by vitor-kato** [comment]
Tried to connect using: mongodb://USER:PASS@gateway/
Not sure because we are using a replicaset if the connection string is in another format?

**Comment by vsnyc** [comment]
The connection string should look like below as documented in [MongoDB docs][1].

mongodb://`<AdminUser`:`<Password>`@`<PrimaryReplicaNodeIp>`:27017, `<SecondaryReplicaNode0Ip>`:27017, `<SecondaryReplicaNode1Ip>`:27017/?authSource=admin&replicaSet=`<MyReplSet>`

Based on your question on how to connect from outside, I'm assuming you already knew that.

> How should I proceed to connect from the outside (internet) to the database?

The short answer is that you should not be doing this. Can the application/workload that connects to the database live in the VPC (or in another VPC or on-prem) that can be privately connected? If that is an option, you can use the private IP address of the instances to connect.

Otherwise, see this [comment][2] on Issue #49 on how to make the database accessible from outside. It is not a recommended best practice so you should evaluate the security implications of making that choice.

[1]: https://docs.mongodb.com/v4.0/reference/connection-string/
[2]: https://github.com/aws-quickstart/quickstart-mongodb/issues/49#issuecomment-614075283
